# Generated by Django 3.2.8 on 2021-10-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifireGroup',
            new_name='ModifierGroup',
        ),
        migrations.RenameModel(
            old_name='ModifireItem',
            new_name='ModifierItem',
        ),
    ]
