# Generated by Django 3.2.8 on 2021-10-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_auto_20211027_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='modifier_group',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifier_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonus.modifiergroup'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='modifiers',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonus.modifieritem'),
        ),
    ]
