# Generated by Django 3.2.8 on 2021-10-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20211027_1450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modifieritem',
            unique_together={('name', 'group')},
        ),
    ]
