# Generated by Django 3.2.8 on 2021-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_alter_modifieritem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
