# Generated by Django 3.2.8 on 2021-10-27 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_menuitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='modifier_group',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='modifiers',
        ),
        migrations.CreateModel(
            name='OrderModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonus.modifiergroup')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonus.modifieritem')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonus.orderitem')),
            ],
        ),
    ]
