# Generated by Django 3.2.8 on 2021-10-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_auto_20211027_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodifier',
            old_name='items',
            new_name='item',
        ),
    ]
