# Generated by Django 3.2.8 on 2021-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_product_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='menu_item',
        ),
    ]
